### ISSUE TITLE
Cant use weapon after 1.8.3 Update

### ISSUE THREAD

**Issue by QuickValve** [thelindat/linden_inventory#184] opened 2021-07-15 06:57 UTC
**Describe the bug**
I cant use any weapon after the new update, i've updated the es_extended

**To Reproduce**
1. Update the inventory
2. Try to use any weapon

**Expected behavior**
I can use any weapon

**Screenshots**
N/A
**Additional context**
N/A

**Comment by Saitama5230** [comment] 2021-07-15 06:59
up, i have this problem too

**Comment by thelindat** [comment] 2021-07-15 08:24
Apparently this was caused by the last PR and should be fixed now.

**Closed** 2021-07-15 12:25 UTC
Labels: bug
